[package]
name = "rustcraft"
version.workspace = true
edition.workspace = true

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[dependencies]
anyhow.workspace = true
avian3d.workspace = true
bevy.workspace = true
bevy-inspector-egui.workspace = true
# bevy-tnua.workspace = true
# bevy-tnua-avian3d.workspace = true
bevy_asset_loader.workspace = true
bevy_editor_pls.workspace = true
bevy_enhanced_input.workspace = true
bevy_mod_mesh_tools.workspace = true
bimap.workspace = true
bytes.workspace = true
derive_more.workspace = true
indexmap.workspace = true
iyes_progress.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
protocol.workspace = true

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[workspace.dependencies]
aes = "0.8.4"
anyhow = { version = "1.0.95", features = ["backtrace"] }
avian3d = { version = "0.2.0", features = ["3d"] }
bevy = { version = "0.15.0", features = ["dynamic_linking", "bevy_dev_tools"] }
bevy-inspector-egui = "0.28.1"
bevy-tnua = "0.21.0"
bevy-tnua-avian3d = "0.2.0"
bevy_asset_loader = { version = "0.22.0", features = ["progress_tracking"] }
bevy_enhanced_input = "0.5.0"
bevy_editor_pls = { git = "https://github.com/sk-1197897/bevy_editor_pls.git", branch = "main" }
bevy_mod_mesh_tools = { git = "https://github.com/Alpyg/bevy_mod_mesh_tools" }
bimap = "0.6.3"
byteorder = "1.5.0"
bytes = "1.9.0"
cfb8 = "0.8.1"
derive_more = { version = "1.0.0", features = ["full"] }
flate2 = "1.0.35"
heck = "0.5.0"
indexmap = { version = "2.7.0", features = ["serde"] }
iyes_progress = { version = "0.13.1", features = ["assets", "async"] }
mem_macros = "1.0.1"
proc-macro2 = "1.0.92"
quote = "1.0.38"
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
syn = "2.0.94"
uuid = "1.11.0"
protocol = { path = "crates/protocol" }
protocol_derive = { path = "crates/protocol_derive" }
